config/routes.rb
Rails.application.routes.draw do
  resources :members
  resources :tournaments
  resources :tournament_types
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :tournament
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :tournament_type
  has_many :members

  validates :tournament_type_id, presence: true
  validates :name, presence: true
  validates :members, length: { minimum: 7, too_short: "%{count} members minimum" }
  accepts_nested_attributes_for :members
end

app/models/tournament_type.rb
class TournamentType < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :type_id, :tournament_id, :status_id)
    end
end

app/controllers/tournament_types_controller.rb
class TournamentTypesController < ApplicationController
  before_action :set_tournament_type, only: [:show, :edit, :update, :destroy]

  # GET /tournament_types
  # GET /tournament_types.json
  def index
    @tournament_types = TournamentType.all
  end

  # GET /tournament_types/1
  # GET /tournament_types/1.json
  def show
  end

  # GET /tournament_types/new
  def new
    @tournament_type = TournamentType.new
  end

  # GET /tournament_types/1/edit
  def edit
  end

  # POST /tournament_types
  # POST /tournament_types.json
  def create
    @tournament_type = TournamentType.new(tournament_type_params)

    respond_to do |format|
      if @tournament_type.save
        format.html { redirect_to @tournament_type, notice: 'Tournament type was successfully created.' }
        format.json { render :show, status: :created, location: @tournament_type }
      else
        format.html { render :new }
        format.json { render json: @tournament_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournament_types/1
  # PATCH/PUT /tournament_types/1.json
  def update
    respond_to do |format|
      if @tournament_type.update(tournament_type_params)
        format.html { redirect_to @tournament_type, notice: 'Tournament type was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament_type }
      else
        format.html { render :edit }
        format.json { render json: @tournament_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournament_types/1
  # DELETE /tournament_types/1.json
  def destroy
    @tournament_type.destroy
    respond_to do |format|
      format.html { redirect_to tournament_types_url, notice: 'Tournament type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament_type
      @tournament_type = TournamentType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_type_params
      params.require(:tournament_type).permit(:name)
    end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
    @members = Member.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    #params[:tournament][:member]

    respond_to do |format|
      if @tournament.save
        @tournament.members.build

        # calculation count rounds
        tours_count = Math.log2(@tournament.members.count).floor

        tours_count.each do |tour|

        end

        byebug

        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :status_id, :start_at, :tournament_type_id, members_attributes: [:id, :name])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @tournaments = Tournament.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/tournament_types_helper.rb
module TournamentTypesHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tournaments</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">GI Турниры</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">

        <li><a href="/">Главная</a></li>
        <li><a href="/tournaments">Все</a></li>
        <% TournamentType.all.each do |type| %>
            <li><a href="/tournament_types/<%= type.id%>"> <%= type.name%></a></li>
        <%end%>
      </ul>
    </div>
  </nav>


  <div class="container">
    <%= yield %>
  </div>





  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Footer Content</h5>
          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        © 2014 Copyright Text
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>

  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :member_name %>
  </div>

  <div class="field">
    <%= form.label :type_id %>
    <%= form.number_field :type_id, id: :member_type_id %>
  </div>

  <div class="field">
    <%= form.label :tournament_id %>
    <%= form.number_field :tournament_id, id: :member_tournament_id %>
  </div>

  <div class="field">
    <%= form.label :status_id %>
    <%= form.number_field :status_id, id: :member_status_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Tournament</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.type_id %></td>
        <td><%= member.tournament_id %></td>
        <td><%= member.status_id %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @member.type_id %>
</p>

<p>
  <strong>Tournament:</strong>
  <%= @member.tournament_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @member.status_id %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/tournament_types/_form.html.erb
<%= form_with(model: tournament_type, local: true) do |form| %>
  <% if tournament_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tournament_type.errors.count, "error") %> prohibited this tournament_type from being saved:</h2>

      <ul>
      <% tournament_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :tournament_type_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tournament_types/edit.html.erb
<h1>Editing Tournament Type</h1>

<%= render 'form', tournament_type: @tournament_type %>

<%= link_to 'Show', @tournament_type %> |
<%= link_to 'Back', tournament_types_path %>

app/views/tournament_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tournament Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournament_types.each do |tournament_type| %>
      <tr>
        <td><%= tournament_type.name %></td>
        <td><%= link_to 'Show', tournament_type %></td>
        <td><%= link_to 'Edit', edit_tournament_type_path(tournament_type) %></td>
        <td><%= link_to 'Destroy', tournament_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament Type', new_tournament_type_path %>

app/views/tournament_types/new.html.erb
<h1>New Tournament Type</h1>

<%= render 'form', tournament_type: @tournament_type %>

<%= link_to 'Back', tournament_types_path %>

app/views/tournament_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tournament_type.name %>
</p>

<%= link_to 'Edit', edit_tournament_type_path(@tournament_type) %> |
<%= link_to 'Back', tournament_types_path %>

app/views/tournaments/_form.html.erb
<div class="row card-panel">

  <%= form_with(model: tournament, local: true, class: "col s12") do |form| %>
      <% if tournament.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% tournament.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

    <div class="row">
      <div class="input-field col s12">
        <%= form.text_field :name, id: :tournament_name, class: "validate" %>
        <%= form.label :name%>
      </div>
    </div>

      <div class="row">
        <div class="input-field col s12">
          <%= form.select :tournament_type_id, TournamentType.pluck(:name,:id), {prompt: "Тип турнира"},
                          id: :tournament_type_id%>
          <label>Тип Турнира</label>
        </div>
      </div>


     <div class="row card-panel indigo lighten-5">
       <%= form.date_select :start_at, id: :tournament_start_at, class: "mdl-textfield__input form-control" %>
     </div>

      <% i = 0%>
     <div class="row">
        <div id="members">
            <%= form.fields_for :members, @members do |member_fields| %>
              <div class="row member_item">
                <div class="field">
                  <%= member_fields.label :name %>
                  <%= member_fields.text_field :name, id: :member_name, placeholder: "Введите имя участника",
                                               class: "textfield__input form-control" %>
                </div>
              </div>
                <% i += 1%>
            <% end %>

        </div>

       <a data-counter="<%= i%>" class="btn-floating btn-large waves-effect waves-light red" id="new_member_btn"><i class="material-icons">add</i></a>

       <!--<p>Количество раундов: <span>3</span></p>-->

       <!--<p><a href="">Добавить 8 участников</a></p>-->
       <p><a href="#members" id="sortMembers">Сортировать участников</a></p>
     </div>

      <div class="row">
        <%= form.submit 'Создать', class: "mdl-button mdl-js-button mdl-button--raised mdl-button--accent" %>
      </div>

  <% end %>
</div>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form', tournament: @tournament %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Турниры</h1>

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th>Тип</th>
      <th>Дата старта</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.name %></td>
        <td><%= tournament.tournament_type.name %></td>
        <td><%= tournament.start_at %></td>
        <td><%= link_to 'Show', tournament %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый турнир', new_tournament_path, {class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored"} %>

app/views/tournaments/new.html.erb
<h1>Новый турнир</h1>

<%= render 'form', tournament: @tournament %>

<%= link_to 'Назад', tournaments_path %>

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tournament.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tournament.status_id %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @tournament.start_at %>
</p>

<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>

app/views/welcome/index.html.erb
<h1>GI Турниры</h1>
<p>Список турниров</p>

<% @tournaments.each do |tournament|%>
    <div class="demo-card-square mdl-card mdl-shadow--2dp">
      <div class="mdl-card__title mdl-card--expand">
        <h2 class="mdl-card__title-text"><%= tournament.tournament_type ? tournament.tournament_type.id : nil%></h2>
      </div>
      <div class="mdl-card__supporting-text">
        <%= tournament.name%>
      </div>
      <div class="mdl-card__actions mdl-card--border">
        <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
          View Updates
        </a>
      </div>
    </div>
<% end%>

<style>
  .demo-card-square.mdl-card {
    width: 320px;
    height: 320px;
  }
  .demo-card-square > .mdl-card__title {
    color: #fff;
    background:
        url('../assets/demos/dog.png') bottom right 15% no-repeat #46B6AC;
  }
</style>